language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 2.0.0
install:
before_script:
script:
- dotnet build -c Release
- dotnet test test/Bitfinex.Client.Websocket.Tests -c Release
deploy:
  provider: script
  skip_cleanup: true
  script:
    - cd src/Bitfinex.Client.Websocket && dotnet pack -c Release && cd bin/Release && dotnet nuget push *.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
  on:
    branch: master